name: Run tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test